### ISSUE TITLE
For feedback: Interactive walkthrough flow (Mac)

### ISSUE THREAD

**Issue by kntsoriano** [exercism/interactive-cli-walkthrough#1]
This is my first pass on creating the interactive walkthrough flow for Mac. I decided to do the instructions for Mac as it is the platform I'm most familiar with. As discussed before, once we converge on a good candidate for a first version, we can ask people to help :)

## Flowchart
![exercism install instructions 1](https://user-images.githubusercontent.com/1901520/29865826-1f6e40ee-8da9-11e7-9737-5692f5728a52.png)

Boxes marked with a questions mark are paths I haven't thought about yet.

## Discussion
In order to guide our discussion, I've outlined the principles we've discussed in https://github.com/exercism/reboot/issues/116.

### Nobody should ever feel stupid
- We're not at this point, yet. I think this would matter more on how we word the instructions. We will revisit this once I've written the guide with instructions.

### Nobody should ever feel stuck
- For every action that the user performs, there must be a way to confirm if they're correct. From personal experience, I noticed that people get stuck when they don't realize that they've done a step incorrectly.
- Add a troubleshooting step for each action in case an error occurs. The user must be able to resolve their problems if they encounter one.
- If troubleshooting doesn't help them, add a step to get in touch with a person that could help them in their issue.
- Instructions should contain screenshots or screencasts for clarity. We might need to rethink how `walkthrough.json` is implemented.

## Next steps
- Once we've ironed out the flow, I'll write instructions and record screencasts.
- After that, we could do a small user test. Also, as discussed, we should also draft our suggestions / protocols for user testing by this point.

**Comment by kytrinyx** [comment]
> Nobody should ever feel stupid
> [...] I think this would matter more on how we word the instructions. We will revisit this once I've written the guide with instructions.

I think that's a good decision.

> I noticed that people get stuck when they don't realize that they've done a step incorrectly.

This is a superb observation! I think that the way you're thinking about the overall flowchart is exactly right: question/response and action/verification.

> Add a troubleshooting step for each action in case an error occurs.

Wise. I wonder if there is a way we can also get people to submit their errors so we can see when there are edge cases we hadn't thought of and figure out when we need to add more troubleshooting steps.

> If troubleshooting doesn't help them, add a step to get in touch with a person that could help them in their issue.

Yeah, maybe we can have a dedicated channel for this where people can help troubleshoot onboarding.

> Instructions should contain screenshots or screencasts for clarity. We might need to rethink how `walkthrough.json` is implemented.

Could we link to this rather than embedding it? I think I need to understand better how screenshots/screencasts play in. Maybe @nicolechalmers has thoughts on this question, as well.

> Once we've ironed out the flow, I'll write instructions and record screencasts.

Excellent!

> After that [...] user test [...] protocols for testing.

Yes to both.

##### Thoughts about the flow chart

My first thought was that we might want to start by asking about OS before "first time" but then I thought about it from a newcomer's perspective, and I think being asked if it's a first time is a much more welcoming start than asking about OS.

The biggest thing that comes to mind is that I think it would be useful to give people an option to do a non-homebrew ("bare"?) installation where they go to the releases, download the correct tarball, untar, move into a good directory, and make sure the directory is in path).

This would also let us point them to that path if they're stuck on homebrew in the "still not fixed" (either contact human or try a bare install).

The last thing is that we won't need to have them configure the CLI, since we will do this interactively the first time they use it.

**Comment by kntsoriano** [comment]
> Wise. I wonder if there is a way we can also get people to submit their errors so we can see when there are edge cases we hadn't thought of and figure out when we need to add more troubleshooting steps.

Yes, that's a good idea :) I also think that we should document fixes when we manage to resolve issues in our troubleshooting channel. We can add that to our self troubleshooting guide. I'm just wary of the possibility that there may be too much information in the self troubleshooting guide, and it might overwhelm our users.

> Could we link to this rather than embedding it? I think I need to understand better how screenshots/screencasts play in. Maybe @nicolechalmers has thoughts on this question, as well.

Yes, linking is possible. I think we should do that first before thinking about embedding media.

> The biggest thing that comes to mind is that I think it would be useful to give people an option to do a non-homebrew ("bare"?) installation where they go to the releases, download the correct tarball, untar, move into a good directory, and make sure the directory is in path).

Yes, we should add this.

> The last thing is that we won't need to have them configure the CLI, since we will do this interactively the first time they use it.

Thanks for this! I'll be removing the steps from the chart.

So, these are the next steps I'm going to take:
1. Remove CLI configuration from the walkthrough
1. Add steps for "bare" installation to the walkthrough
1. Start working on the copy

**Comment by kytrinyx** [comment]
> I'm just wary of the possibility that there may be too much information in the self troubleshooting guide, and it might overwhelm our users.

True, we should keep that in mind. Hopefully it wouldn't be overwhelming, though, if we only have them try one thing at a time.

> So, these are the next steps I'm going to take:

That sounds great!

**Comment by kntsoriano** [comment]
Hi @kytrinyx, here's a first pass on our installation guide for Mac:

https://docs.google.com/forms/d/1cw4e3YfIWH3afR0nMHaSgSpI4fbe96oe0vUx4eb8nVo/edit?usp=sharing

I decided to put it in a Google form because it allows us to visualize the flow better as well as make it easy to edit the copy collaboratively. For making it easier to contribute, I think we can use a tool such as this (Google Form or Typeform), export the form to JSON, then parse the exported JSON to be used by our walkthrough. I noticed while I was making the walkthrough that using an editor such as this helped a lot, it was more visual and provided an easy way to see how the branches went from one to the other.

It'll help to have feedback on the following:
1. I'd like to have feedback on how I wrote the copy. It's still a bit coarse, but I've kept in mind to always be talking with a welcoming tone. Please point out some parts where it didn't seem that way. 1. I'd like to have feedback on how the screenshots / screen recordings were presented. Were they intuitive enough or they didn't help?
1. I'd like to have feedback on how the instructions were structured. Should we use a different one?

Also, I'm unsure how to build the troubleshooting part of the walkthrough right now, as I haven't encountered a problem yet. Do we have old issues or an old troubleshooting guide so we can put something in there?

Looking forward to hear from you!

**Comment by kytrinyx** [comment]
> I decided to put it in a Google form because it allows us to visualize the flow better as well as make it easy to edit the copy collaboratively.

This is clever, and very useful!

> I haven't wrote copy for the troubleshooting part of the walkthrough right now, as I haven't encountered a problem yet.

Let's leave this for now, and describe troubleshooting as something we wish to include once we know what types of problems people run into. That way people can help by running into problems and describing them for us.

I think people who hang out in the gitter chat will also be able to tell us more about the types of problems people have.

Ok, on to feedback.

First I think that the copy is all great for a first pass. We might tweak in a few places, but I don't think this is critical to improve beyond what you have for now. This illustrates really well the tone/voice that we're going for.

I'm really not sure about the screenshots—I think we will need to run this by someone who is unfamiliar with the terminal in order to check this.

In the diagram above you have a box called "install script". I know we have it, and it's probably fine for people who are familiar with working on the command-line, but I don't think it's a good fit for people who are new because it's not very robust, and I'd rather not have to maintain it to the degree necessary if people unfamiliar with the terminal try using it. I'd much rather direct people to the latest release on GitHub and have them download the right one for their machine. We would need to help them figure out whether to install 32 bit or 64 bit, then use tar to extract the archive, then stick it in a reasonable location (e.g. `~/bin`) then make sure `bin` is in their PATH.

Next thing I notice as that you have `zsh` installed, which responds to `which brew` with "brew not found" if it's not installed on the system. In `bash`, the output of `which` for _not found_ is... nothing. No output :(

This is tricky to walk people through as it's pretty confusing.

Another option here would be to direct people to type `brew --version`. Then they'll either get version output, or get

```
-bash: brew: command not found
```

I don't know what this looks like in zsh, though.

Another thing that I noticed as I was walking through the Google Form guide, is that we're having people confirm that homebrew/exercism was installed by looking at the output. For people who are unfamiliar with working on the terminal, this can be problematic for several reasons: if there's a lot of output, their eyes glaze over and they miss things. If the output looks a little bit different they'll often be unsure whether it worked or not.

I'd like to give them a command that they can run that will confirm that it got installed (maybe `brew --version` and `exercism version`). We will probably have to make sure that people don't type

`brew--version` or `brew-version` or `brew —version`, the possibilities for typos are endless.

I made an installation video a long, long time ago. I was not happy with it, but it kind of helped:
https://www.youtube.com/watch?v=TCT4eHGwfaE
People typed things wrong a lot of the time, though, and it caused a lot of support requests.

Even if we give people a command with less output, it will also have slightly different output from system to system and as things evolve, but I think that we'll be better able to control the variables here.

For the "not first time" part of the flow (not developed yet) I'm thinking we need something that bypasses a lot of the hand-holding. Here's a quick attempt:

- Not first time
- OS -> (Mac), (Linux), (Windows)
- [Mac] -> Do you have homebrew? (Yes), (No)
  - [Yes] ->
    - install with: brew install exercism -> (ok, did that)
    - confirm with: exercism version -> (ok, did that)
    - done
  - [No] -> (install homebrew), (download from GitHub)
  - [download from GitHub] -> (I have a 32 bit machine), (I have a 64 bit machine)
    - Go to https://github.com/exercism/cli/releases/latest and download [the correct file name] to your machine -> (ok, did that)
    - Extract archive with: `tar -xzvf exercism-mac-64bit.tgz` (or 32bit if they said 32) -> (ok, did that)
    - Put it in your path -> ok, did that
    - confirm with: exercism version -> (ok, did that)
    - done

OK, I think that's all I can think of. I'm always happy to discuss further, of course!

**Comment by kntsoriano** [comment]
Thank you very much for that! It was very insightful, and I didn't realize all of those while making the tutorial.

To sum it up, here were my takeaways and how I've changed the tutorial to fit them in:

1. Manual installation versus install script

As you've said, the installation script isn't safe for now and we don't want to maintain it. I agree that we should just outline the steps to do manual installation. In the latest iteration of the tutorial, I haven't done this yet, but I will add it. I decided to focus on the other takeaways for now.

2. Zsh vs Bash, inconsistent environments

In the new iteration of the tutorial, I've added annotations to explain the command's output. This ensures us that the user understands what the command returns and could infer whether they've been successful in the step or not. I've also explicitly noted in the tutorial that outputs may differ on each machine. In terms of zsh vs bash, I've decided to put all my screenshots on bash because it's the Mac's default shell.

3. Commands to confirm steps

For each step, I've added a step to verify whether they've done the right thing. This also ties in to introducing a structure to our guides, having an Exercise-Verify loop for each step.

4. Typos

To avoid typos, I wrapped every code example inside a code block and added a recommendation that they copy and paste instead of type the commands.

As for workflow, I've noticed that I have duplicated effort updating the graph and updating the google form. Good thing I got hold of this tool named [Twine](twinery.org) which does both! It's actually for writing non-linear fiction, but it seems to be a good tool to fit our use case.

I also had a better time writing the tutorial because I was able to use Markdown, and I just needed to add a few special commands in order to link cards to one another.

Here's an example of the markup:

```
Having problems opening the terminal on your Mac? You might find a solution to your problem below.

---

## Were you able to open the Terminal?

- [[Yes->Verifying Homebrew Installation]]
- [[No->Talk to a Volunteer]]
```

In this example, "Yes" links to the "Verifying Homebrew installation card". Other markup are standard Markdown.

Once we get lots of cards written with the links also annotated at the end, Twine gives us a clean graph of our story path:

<img width="743" alt="screen shot 2017-09-05 at 6 33 20 pm" src="https://user-images.githubusercontent.com/1901520/30057290-b670d920-9268-11e7-8048-ddd820318250.png">

I'm still thinking about our workflow around this once we get lots of maintainers in.

Here's the rewritten tutorial: http://philome.la/kntsoriano/exercism-install-instructions/play

**Comment by kytrinyx** [comment]
@kntsoriano I'm so sorry I missed this. I've not been checking email for the past few days :(

> To sum it up, here were my takeaways and how I've changed the tutorial to fit them in:

These are excellent changes.

> I got hold of this tool named Twine which does both! It's actually for writing non-linear fiction, but it seems to be a good tool to fit our use case.

That is brilliant. I want there to be a blog post or talk about this eventually! What a great idea.

I think this is ready for feedback from @iHiD, as we're now down to questions about format, visuals, and flow.

**Comment by kntsoriano** [comment]
@kytrinyx No problem! An updated version with tooling is available at this PR: https://github.com/exercism/interactive-cli-walkthrough/pull/2. We could discuss further in there. Maybe @iHiD could take a look at it, too.

**Comment by kntsoriano** [comment]
Closing as we've merged v1 of the walkthrough.
